import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from '@clerk/nextjs'


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={inter.className} suppressHydrationWarning={true}>
            {children}
          <div>
            <ul className="box_container">
              {/* <li>😊</li>
              <li>😂</li>
              <li>🤣</li>
              <li>😘</li>
              <li>😒</li>
              <li>👌</li>
              <li>💕</li>
              <li>😁</li>
              <li>👍</li>
              <li>🙌</li> */}
              <li></li>
              <li></li>
              <li></li>
              <li></li>
              <li></li>
              <li></li>
              <li></li>
              <li></li>
              <li></li>
              <li></li>
            </ul>
          </div>
        </body>
      </html>
    </ClerkProvider>

  );
}
